spring.application.name=humapper-backend

# PostGIS connection
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/humapper}
spring.datasource.username=${DB_USER:humapper}
spring.datasource.password=${DB_PASSWORD:humapper}

# Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect