CREATE TABLE sector (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32)  NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL
);

INSERT INTO sector (code, name) VALUES
    ('CCCM','Camp Coordination and Camp Management'),
    ('EARLY_RECOVERY','Early Recovery'),
    ('EDUCATION','Education'),
    ('ETC','Emergency Telecommunications'),
    ('FSC','Food Security'),
    ('HEALTH','Health'),
    ('LOGISTICS','Logistics'),
    ('NUTRITION','Nutrition'),
    ('PROTECTION','Protection'),
    ('SHELTER','Shelter'),
    ('WASH','Water, Sanitation and Hygiene'),
    ('CASH', 'Cash and Voucher Assistance');