CREATE TABLE activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id BIGINT NOT NULL REFERENCES organizations(id),
    geom geometry(Geometry, 4326) NOT NULL,
    status VARCHAR(32) NOT NULL,
    start_date DATE,
    end_date DATE,
    target_people INTEGER,
    description TEXT,
    last_updated TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX activity_geom_idx ON activity USING GIST (geom);

CREATE TABLE activity_sector (
    activity_id BIGINT NOT NULL REFERENCES activity(id) ON DELETE CASCADE,
    sector_id BIGINT NOT NULL REFERENCES sector(id),
    PRIMARY KEY (activity_id, sector_id)
);